language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.gradle
script:
  - ./gradlew clean
  - ./gradlew test
  - ./gradlew bootJar -x test
deploy:
  provider: heroku
  api_key:
    secure: 77ea18dc-50f5-4afd-829e-e9a1a373b688
  app: todo-list-data-api
  on:
    repo: zjx-immersion/todo-list-api
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false